---
- hosts: all
  become: true

  tasks:
  - name: Ensure chrony (for time synchronization) is installed.
    dnf:
      name: chrony
      state: present

  - name: Ensure chrony is running.
    service:
      name: chronyd
      state: started
      enabled: yes

# The same as the above play, but in super-compact form!
- hosts: all
  become: true
  tasks:
  - dnf: name=chrony state=present
  - service: name=chronyd state=started enabled=yes
